[custom]

; ======================
; 自定义策略组
; ======================

custom_proxy_group=loadbalance`load-balance`新加坡`印尼`土耳其`德国`澳大利亚`菲律宾`俄罗斯`韩国`http://cp.cloudflare.com/generate_204`300`round-robin

custom_proxy_group=美国`url-test`美国`https://cp.cloudflare.com/generate_204`300,,150

custom_proxy_group=日本`url-test`日本`http://cp.cloudflare.com/generate_204`300,,150

custom_proxy_group=新加坡`url-test`新加坡`http://cp.cloudflare.com/generate_204`300,,150

custom_proxy_group=新加坡loadbalance`load-balance`新加坡`http://cp.cloudflare.com/generate_204`300`round-robin
