[[custom_groups]]
name = "loadbalance"
type = "load-balance"
rule = [
  "[]新加坡 01",
  "[]新加坡 02",
  "[]新加坡 03",
  "[]印尼 01",
  "[]土耳其 01",
  "[]德国 01",
  "[]澳大利亚 01",
  "[]菲律宾 01",
  "[]俄罗斯 01",
  "[]韩国 01"
]
url = "http://cp.cloudflare.com/generate_204"
interval = 300
strategy = "round-robin"
disable_udp = false


[[custom_groups]]
name = "美国"
type = "url-test"
rule = [
  "[]美国 01",
  "[]美国 02",
  "[]美国 03"
]
url = "https://cp.cloudflare.com/generate_204"
interval = 300
tolerance = 150
disable_udp = false


[[custom_groups]]
name = "日本"
type = "url-test"
rule = [
  "[]日本 01",
  "[]日本 02",
  "[]日本 03"
]
url = "http://cp.cloudflare.com/generate_204"
interval = 300
tolerance = 150
disable_udp = false