[custom]

; ======================
; 自定义策略组
; ======================

custom_proxy_group=loadbalance`load-balance`[]🇸🇬 新加坡 01`[]🇸🇬 新加坡 02`[]🇸🇬 新加坡 03`[]🇮🇩 印尼 01`[]🇹🇷 土耳其 01`[]🇩🇪 德国 01`[]🇦🇺 澳大利亚 01`[]🇵🇭 菲律宾 01`[]🇷🇺 俄罗斯 01`[]🇰🇷 韩国 01`http://cp.cloudflare.com/generate_204`300

custom_proxy_group=美国`url-test`[]🇺🇲 美国 01`[]🇺🇲 美国 02`[]🇺🇲 美国 03`https://cp.cloudflare.com/generate_204`300,,150

custom_proxy_group=日本`url-test`[]🇯🇵 日本 01`[]🇯🇵 日本 02`[]🇯🇵 日本 03`http://cp.cloudflare.com/generate_204`300,,150

custom_proxy_group=新加坡`url-test`[]🇸🇬 新加坡 01`[]🇸🇬 新加坡 02`[]🇸🇬 新加坡 03`http://cp.cloudflare.com/generate_204`300,,150